apiVersion: v1

kind: ReplicationController

metadata:

  name: web-server-rc

spec:

  replicas: 3

  selector:

    app: web-server

  template:

    metadata:

      name: web-server-pod

      labels:

        app: web-server

    spec:

      containers:

      - name: web-server

        image: gcr.io/my-tutorial01/web-server:v1

        imagePullPolicy: Always

        ports:

        - containerPort: 3000

