
apiVersion: v1

kind: Service

metadata:

  name: web-server-svc

spec:

  selector:

    app: web-server

  ports:

    - port: 80

      protocol: TCP

      targetPort: 3000

  type: LoadBalancer
