apiVersion: v1

kind: ReplicationController

metadata:

  name: weather-app-rc

spec:

  replicas: 3

  selector:

    app: weather-app

  template:

    metadata:

      name: weather-app-pod

      labels:

        app: weather-app

    spec:

      containers:

      - name: weather-app

        image: gcr.io/my-tutorial01/weather-app:v1

        imagePullPolicy: Always

        ports:

        - containerPort: 3000

