
apiVersion: v1

kind: Service

metadata:

  name: weather-app-svc

spec:

  selector:

    app: weather-app

  ports:

    - port: 80

      protocol: TCP

      targetPort: 3000

  type: LoadBalancer
